### PR TITLE
chore: publish ai lab v1.1.1

### PR DESCRIPTION
**Pull request by feloy**
AI Lab v1.1.1

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]
Thanks!

**Comment by benoitf** [comment]
should be on hold for now

**Review by deboer-tim — APPROVED** [review]

**Comment by benoitf** [comment]
@feloy could you use the latest README from https://github.com/containers/podman-desktop-extension-ai-lab/blob/main/README.md, this one has some missing images and missing roadmap

**Comment by benoitf** [comment]
@feloy if you can fix the DCO check

**Review by benoitf — APPROVED** [review]

**Pull request merged**
