### PR TITLE
feat: layers explorer v0.2.0

### PR DESCRIPTION
**Pull request by feloy**
Image Layers Explorer v0.2.0

To merge only when Podman Desktop v1.13.0 is out

Fixes https://github.com/containers/podman-desktop-extension-layers-explorer/issues/35

### CODE REVIEW

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop-catalog/blob/509986222ec311fcf830e09f84b1dc5302c15a13/api/extensions.json#L668

**Review by benoitf — APPROVED** [review]
approving

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by feloy** [comment]
updated to v0.2.0

**Review by benoitf — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
