### PR TITLE
chore: Update OpenShift local to v1.0.3

### PR DESCRIPTION
**Pull request by benoitf**
Change-Id: Ifefb2487f34090ca925edc7c1fdfb16bba78f436

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by gbraad** [comment]
Can we not just download the 'latest' instead ?

**Comment by benoitf** [comment]
no, people should be able to downgrade or to use a specific version.

**Comment by gbraad** [comment]
> or to use a specific version.

This introduces an additional burden on our end. At the moment we do not enforce versions to be aligned with the extension, plus there is n support for any version < N-1.

So, no... I would not agree to this. That is not in line with the CCS we set up with the support team.

**Review by themr0c — APPROVED** [review]

**Pull request merged**
