### PR TITLE
chore: add bootc 0.2.0 release

### PR DESCRIPTION
**Pull request by deboer-tim**
Add the bootc 0.2.0 release to the catalog, fix the date on previous releases, and add a couple keywords.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
I notice that README is using relative links

[]

so it can't work in Podman Desktop as we're missing the context (the full path)

(not sure it'll be rendered correctly but I think it should be fixed to have only absolute links)

I notice as well that the TOC is breaking the navigation in Podman Desktop (as it'll jump to different place in Podman Desktop)

**Comment by deboer-tim** [comment]
Both of these things are relatively common in READMEs - do you think we should say 'but not in extension READMEs if you want to be in the catalog', do some post-processing when adding to the catalog, do some processing/filtering inside Podman Desktop, or something else?

**Comment by benoitf** [comment]
I think for most of VS code extensions or other tools where you provide a README ,people have replaced their README to make it working nicely on the marketplace

so probably either warnings or errors in PR checks for the catalog

( Or nothing and it's up to the user)

**Comment by benoitf** [comment]
example https://raw.githubusercontent.com/redhat-developer/vscode-java/master/README.md

**Comment by deboer-tim** [comment]
Added comments to https://github.com/containers/podman-desktop-extension-bootc/issues/138, will follow up there.

**Pull request merged**
