### PR TITLE
add openshift-checker 0.1.5

### PR DESCRIPTION
**Pull request by feloy**

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
I don't know if it's possible to split lines in some renderer block fields by wrapping lines

until https://github.com/containers/podman-desktop/issues/6930 is fixed

image

**Comment by feloy** [comment]
It depends which window width we want to consider. If it is the default width, this seems reasonable, as this will make lines of ~80 characters.

But if we are considering the minimal width, this will make lines of ~50 characters, which could be weird if the window if larger.

**Comment by benoitf** [comment]
maybe try 80 chars ?

**Comment by feloy** [comment]
The README is updated with code blocks limited to 80 cols

**Review by benoitf — APPROVED** [review]
awesome

**Pull request merged**
