### PR TITLE
feat: bootc 1.4.0 release

### PR DESCRIPTION
**Pull request by deboer-tim**

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
if you could add the minimum podman desktop version required for this version

example: https://github.com/containers/podman-desktop-catalog/blob/8715d52728e0b09f95c7de9021386881965c58d9/api/extensions.json#L668

**Comment by deboer-tim** [comment]
Sure, added. (same value, I think we depend on API that was added in 1.12 and no reason to go earlier)

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
need to wait @containers/podman-desktop-qe-reviewers before merging ?

**Comment by deboer-tim** [comment]
@cbr7 Want to confirm or run any tests? You can install the release manually via `ghcr.io/containers/podman-desktop-extension-bootc:1.4.0`, I've confirmed it installs and builds

**Comment by cbr7** [comment]
@deboer-tim will check it out tomorrow.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by cbr7** [comment]
@odockal and I have checked this release on windows, mac and linux and it seems to work fine, with the noted exception that there is a known issue with building cross arch images as reported in https://github.com/containers/podman-desktop-extension-bootc/issues/808. I think it's fine to release.

**Pull request merged**
